import { Routes, Route } from "react-router-dom";

import Home from "../../routes/home/home";
import AboutUs from "../../routes/about-us/about-us";
import Events from "../../routes/events/events";
import NewStudents from "../../routes/new-students/new-students";
import ContactUs from "../../routes/contact-us/contact-us";
import EventDisplay from "../../routes/event-display/event-display";

const Layout = () => {
  const ws = {
    imageUrl: require("../../assets/carousle/welcome-social.JPG"),
    text: "The Indian Students Association (ISA) hosts a welcome social at the beginning of each semester to facilitate introductions among new students and provide them with valuable information about the university and campus. The event serves as an ice breaker, featuring food and games that encourage attendees to connect with fellow students, including former, current, and new faces at Virginia Tech (VT).\n\nIn addition to the social activities, the ISA provides a detailed overview of upcoming events and highlights various on-campus clubs, communities, and sports teams. This information is designed to help new students acclimate to university life and fully engage in the campus community.\n\nOverall, the ISA's welcome social serves as a vital resource for incoming students, providing them with both practical information and an opportunity to connect with their peers.",
  };
  const da = {
    imageUrl: require("../../assets/carousle/dandiya.jpeg"),
    text: "Dandiya is a traditional folk dance that originated in the state of Gujarat, India. The dance is performed during the Hindu festival of Navratri. ISA conducts a single Dandiya dance night in the fall semester.\n\nThe dance is performed by men and women, who wear colorful traditional attire and hold small wooden sticks called dandiyas. Participants move in a circular pattern and strike their sticks together in time with the music, creating a rhythmic and lively dance that is full of energy and enthusiasm.\n\nDandiya is not only a cultural tradition but also a social event, providing an opportunity for people to come together and celebrate. The dance is often performed in large groups, with people of all ages joining in and enjoying the festive atmosphere.\n\nIn recent years, Dandiya has become popular outside of India and is now performed in many countries around the world. It is a testament to the power of cultural traditions to bring people together and create a sense of community across borders and boundaries.\n\nThe festival is a reminder of the power of music, dance, and community to bring people together and create a sense of joy and belonging. We invite everyone to come and experience the magic of Dandiya and celebrate the richness and diversity of Indian culture.",
  };
  const di = {
    imageUrl: require("../../assets/carousle/diwali.jpeg"),
    text: "Diwali, also known as the Festival of Lights, is one of the most widely celebrated Hindu festivals in the world. It is a five-day festival that takes place after Dandiya, usually in October or November, and is celebrated by millions of people across India and around the globe.\n\nThe festival of Diwali has many different meanings and traditions associated with it, but it is primarily a celebration of the victory of good over evil, and the triumph of light over darkness. During Diwali, people light diyas, or small oil lamps, which symbolize the triumph of light over darkness, and decorate their homes with colorful rangolis, or patterns made with colored powders.\n\nOne of the most popular traditions of Diwali is the exchange of gifts and sweets among friends and family members. People also prepare special foods and dishes, and participate in prayer and meditation to honor the Hindu deities.\n\nIn addition to the religious significance, Diwali also has cultural and social significance. It is a time when people come together to celebrate, share, and connect with each other, regardless of their caste, creed, or religion. The festival is celebrated with great enthusiasm and joy, and is a time for people to forget their differences and come together in harmony and unity.\n\nThe Indian Students Association (ISA) is proud to present a special cultural show, followed by fireworks and an authentic Indian dinner. This event is designed to showcase the vibrant and diverse culture of India and provide attendees with a memorable experience.\n\nThe cultural show will feature a range of performances, including traditional dances, music, and other artistic expressions. These performances will highlight the rich heritage and customs of India, and provide attendees with a unique and immersive cultural experience.\n\nFollowing the cultural show, attendees will be treated to a dazzling display of fireworks that will light up the night sky. The fireworks display is sure to be a highlight of the evening, and will provide a memorable and visually stunning experience for all.\n\nFinally, attendees will be invited to enjoy an authentic Indian dinner, featuring a range of delicious and flavorful dishes that are sure to tantalize the taste buds. The dinner will be a celebration of the rich culinary traditions of India, and will provide attendees with a taste of the diverse and flavorful cuisine that India has to offer.\n\nOverall, the cultural show, fireworks, and Indian dinner organized by ISA promises to be an unforgettable evening of celebration, entertainment, and cultural enrichment. We invite everyone to come and join us for this special event, and experience the beauty and richness of Indian culture firsthand.",
  };
  const ho = {
    imageUrl: require("../../assets/holi-3.jpg"),
    text: 'Holi, also known as the Festival of Colors, is a popular Hindu festival that is celebrated in India and other parts of the world. The festival is usually held in late February or early March and is a time for people to come together and celebrate the arrival of spring.\n\nOne of the most distinctive aspects of Holi is the use of colored powders, which are thrown and smeared on each other in a playful and joyous manner. This tradition symbolizes the breaking down of barriers and the coming together of people from different backgrounds and walks of life.\n\nIn addition to the colorful festivities, Holi also has religious significance. It is a time to celebrate the victory of good over evil and the triumph of light over darkness. During Holi, people also gather to offer prayers and offerings to deities, seeking their blessings for prosperity and happiness.\n\nAnother important tradition of Holi is the sharing of sweets and other traditional foods with friends and family members. People also gather for feasts and parties, and there is a general sense of warmth, joy, and togetherness that permeates the festival.\n\nThe Indian Students Association (ISA) is excited to present our most popular event on campus, the "Holi: Color War" celebration. This event is designed to bring together students from diverse backgrounds to celebrate the joyous and vibrant festival of Holi.\n\nDuring the event, participants gather together to play with colored powders (no water), creating a playful and colorful environment that is full of energy and excitement. This tradition is a key part of the Holi festival and represents the breaking down of social barriers and the coming together of people from all walks of life.\n\nTo enhance the experience, ISA provides complimentary snacks to all participants, allowing them to refuel and recharge before continuing the festivities. The snacks are a mix of traditional and modern treats, providing a taste of both Indian culture and contemporary snacks.\n\nOverall, the Holi: Color War celebration organized by ISA is an unforgettable experience that allows students to come together, enjoy the full experience of Holi, and connect with each other in a joyful and playful environment. We invite everyone to come and join us for this special event and celebrate the richness and diversity of Indian culture.',
  };
  const isf = {
    imageUrl: require("../../assets/carousle/international-cafe-hours.jpg"),
    text: "The International Street Fair at Virginia Tech is an annual event that celebrates the diverse cultures and traditions of the university's international community. This vibrant event is open to the public and is held in the heart of the Virginia Tech campus.\n\nDuring the International Street Fair, attendees have the opportunity to explore a wide range of cultures and traditions from around the world. The fair features booths and displays from various student organizations, each showcasing their own unique heritage and customs. Visitors can sample traditional foods, learn about different languages and customs, and participate in interactive activities that are designed to provide a deeper understanding and appreciation of international cultures.\n\nIn addition to the cultural exhibits, the International Street Fair also features a range of entertainment options, including live music and dance performances, as well as games and activities for all ages. These activities are designed to bring together people from all backgrounds and provide a fun and engaging atmosphere for everyone to enjoy.\n\nISF at Virginia Tech is a celebration of the diverse and vibrant international community that is an integral part of the university. It is a time to come together, learn about different cultures, and celebrate the unique traditions and customs that make our world such a rich and beautiful place. We invite everyone to come and join us for this special event and experience the magic of the International Street Fair.",
  };

  return (
    <div className="layout">
      <Routes>
        <Route index element={<Home />} />
        <Route path="#aboutus" element={<AboutUs />} />
        <Route path="#contactus" element={<ContactUs />} />
        <Route path="events/" element={<Events />}>
          <Route index element={<EventDisplay elist={ho} />} />
          <Route path="welcomesocial" element={<EventDisplay elist={ws} />} />
          <Route path="dandiya" element={<EventDisplay elist={da} />} />
          <Route path="diwali" element={<EventDisplay elist={di} />} />
          <Route path="holi" element={<EventDisplay elist={ho} />} />
          <Route path="isf" element={<EventDisplay elist={isf} />} />
        </Route>
        <Route path="newstudents" element={<NewStudents />} />
      </Routes>
    </div>
  );
};

export default Layout;
